task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views

urlpatterns = [
    path('statuses/', views.StatusesView.as_view(), name='statuses'),
    path(
        'statuses/create/',
        views.CreateStatusView.as_view(),
        name='create_status',
    ),
    path(
        'statuses/<int:pk>/update/',
        views.UpdateStatusView.as_view(),
        name='update_status',
    ),
    path(
        'statuses/<int:pk>/delete/',
        views.DeleteStatusView.as_view(),
        name='delete_status',
    ),
    path('tasks/', views.TaskView.as_view(), name='tasks'),
    path(
        'tasks/create/',
        views.CreateTaskView.as_view(),
        name='create_task',
    ),
    path(
        'tasks/<int:pk>/update/',
        views.UpdateTaskView.as_view(),
        name='update_task',
    ),
    path(
        'tasks/<int:pk>/delete/',
        views.DeleteTaskView.as_view(),
        name='delete_task',
    )
]

task_manager/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('task_manager.users.urls')),
    path('', include('task_manager.tasks.urls')),
    prefix_default_language=False
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task_manager/tasks/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Status(models.Model):
    """Statuses."""
    name = models.CharField('Имя', max_length=100, unique=True)
    created_at = models.DateTimeField('created_at', default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Стaтусы'


class Task(models.Model):
    """Tasks."""
    name = models.CharField('Имя', max_length=100)
    created_at = models.DateTimeField('created_at', default=timezone.now)
    description = models.TextField('Описание', null=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='task_author',
        verbose_name='Автор',
    )
    performer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='task_performer',
        verbose_name='Исполнитель',
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.CASCADE,
        verbose_name='Статус',
    )

task_manager/tasks/forms.py
from django import forms
from task_manager.tasks import models


class StatusForm(forms.ModelForm):
    """Form of status."""
    class Meta:
        model = models.Status
        fields = ('name',)
        widgets = {'name': forms.TextInput(attrs={
            'class': 'form-control border',
            'placeholder': 'Имя',
        })}


class TaskForm(forms.ModelForm):
    """Form of status."""
    class Meta:
        model = models.Task
        fields = ('name', 'description', 'status', 'performer',)
        widgets = {'name': forms.TextInput(attrs={
            'class': 'form-control border',
            'placeholder': 'Имя',
        })}

task_manager/tasks/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import HttpResponseRedirect

from task_manager.tasks import models, forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy


class StatusesView(LoginRequiredMixin, ListView):
    model = models.Status
    queryset = models.Status.objects.all()
    template_name = 'statuses/statuses.html'
    login_url = reverse_lazy('login')
    redirect_field_name = 'statuses'


class CreateStatusView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = models.Status
    form_class = forms.StatusForm
    template_name = 'statuses/create_status.html'
    success_url = reverse_lazy('statuses')
    success_message = gettext_lazy('Статус создан!')
    login_url = reverse_lazy('login')
    redirect_field_name = 'create_status'


class UpdateStatusView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = models.Status
    form_class = forms.StatusForm
    template_name = 'statuses/update_status.html'
    success_url = reverse_lazy('statuses')
    success_message = gettext_lazy('Статус изменен!')
    login_url = reverse_lazy('login')
    redirect_field_name = 'update_status'


class DeleteStatusView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = models.Status
    template_name = 'statuses/delete_status.html'
    success_url = reverse_lazy('statuses')
    login_url = reverse_lazy('login')
    redirect_field_name = 'delete_status'

    def get_success_url(self):
        messages.success(self.request, gettext_lazy('Статус удален!'))
        return self.success_url


class TaskView(LoginRequiredMixin, ListView):
    model = models.Task
    queryset = models.Task.objects.all()
    template_name = 'tasks/tasks.html'
    login_url = reverse_lazy('login')
    redirect_field_name = 'tasks'


class CreateTaskView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = models.Task
    form_class = forms.TaskForm
    template_name = 'tasks/create_task.html'
    success_url = reverse_lazy('tasks')
    success_message = gettext_lazy('Задача создана!')
    login_url = reverse_lazy('login')
    redirect_field_name = 'create_task'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.pk
        return super().form_valid(form)


class UpdateTaskView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = models.Task
    form_class = forms.TaskForm
    template_name = 'tasks/update_task.html'
    success_url = reverse_lazy('tasks')
    success_message = gettext_lazy('Задача изменена!')
    login_url = reverse_lazy('login')
    redirect_field_name = 'update_task'


class DeleteTaskView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = models.Task
    template_name = 'tasks/delete_task.html'
    success_url = reverse_lazy('tasks')
    login_url = reverse_lazy('login')
    redirect_field_name = 'delete_task'
    error_message = gettext_lazy(
        'Задачу может удалить только её автор.',
    )

    def dispatch(self, request, *args, **kwargs):
        if self.model.objects.get(
            pk=kwargs['pk']
        ).author_id != self.request.user.pk:
            messages.error(request, self.error_message)
            return HttpResponseRedirect('/tasks/')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, gettext_lazy('Задача удалена!'))
        return self.success_url

templates/tasks/create_task.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
     <h1 class="jumbotron text-center">{% trans 'Создать задачу' %}</h1>

</form>
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-primary my-2" type="submit">{% trans 'Создать' %}</button>
  </form>

{% endblock content %}

templates/tasks/delete_task.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
     <h1 class="jumbotron text-center">{% trans 'Удалить задачу' %}</h1>
    <form method="post">
    {% csrf_token %}
      <p>{% trans 'Вы уверены, что хотите удалить задачу'%} <strong>"{{ object.name }}"</strong>?</p>
    <button class="btn btn-danger" type="submit">{% trans 'Удалить' %}</button>
  </form>

{% endblock content %}

templates/tasks/tasks.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <h1 class="jumbotron text-center">{% trans 'Задачи' %}</h1>

          <h5><a href="{% url 'create_task' %}" class="text-black">{% trans 'Создать задачу' %}</a></h5>

        <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>{% trans 'Имя' %}</th>
                <th>{% trans 'Статус' %}</th>
                <th>{% trans 'Автор' %}</th>
                <th>{% trans 'Исполнитель' %}</th>
                <th>{% trans 'Дата создания' %}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for task in task_list %}
                <tr>
                    <td>{{ task.id }}</td>
                    <td>{{ task.name }}</td>
                    <td>{{ task.status }}</td>
                    <td>{{ task.author }}</td>
                    <td>{{ task.performer }}</td>
                    <td>{{ task.created_at }}</td>
                    <td>
                        <a href={% url 'update_task' task.id %} >{% trans 'Изменить' %}</a>
                        <br>
                        <a href={% url 'delete_task' task.id %}>{% trans 'Удалить' %}</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


{% endblock content %}

templates/tasks/update_task.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
     <h1 class="jumbotron text-center">{% trans 'Изменить задачу' %}</h1>
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-primary my-2" type="submit">{% trans 'Изменить' %}</button>
  </form>

{% endblock content %}